config/routes.rb
Rails.application.routes.draw do
  resources :lorries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lorry.rb
class Lorry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lorries_controller.rb
class LorriesController < ApplicationController
  before_action :set_lorry, only: [:show, :edit, :update, :destroy]

  # GET /lorries
  # GET /lorries.json
  def index
    @lorries = Lorry.all
  end

  # GET /lorries/1
  # GET /lorries/1.json
  def show
  end

  # GET /lorries/new
  def new
    @lorry = Lorry.new
  end

  # GET /lorries/1/edit
  def edit
  end

  # POST /lorries
  # POST /lorries.json
  def create
    @lorry = Lorry.new(lorry_params)

    respond_to do |format|
      if @lorry.save
        format.html { redirect_to @lorry, notice: 'Lorry was successfully created.' }
        format.json { render :show, status: :created, location: @lorry }
      else
        format.html { render :new }
        format.json { render json: @lorry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lorries/1
  # PATCH/PUT /lorries/1.json
  def update
    respond_to do |format|
      if @lorry.update(lorry_params)
        format.html { redirect_to @lorry, notice: 'Lorry was successfully updated.' }
        format.json { render :show, status: :ok, location: @lorry }
      else
        format.html { render :edit }
        format.json { render json: @lorry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lorries/1
  # DELETE /lorries/1.json
  def destroy
    @lorry.destroy
    respond_to do |format|
      format.html { redirect_to lorries_url, notice: 'Lorry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lorry
      @lorry = Lorry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lorry_params
      params.fetch(:lorry, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lorries_helper.rb
module LorriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RukayatFirstRailsApl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lorries/_form.html.erb
<%= form_with(model: lorry, local: true) do |form| %>
  <% if lorry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lorry.errors.count, "error") %> prohibited this lorry from being saved:</h2>

      <ul>
      <% lorry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lorries/edit.html.erb
<h1>Editing Lorry</h1>

<%= render 'form', lorry: @lorry %>

<%= link_to 'Show', @lorry %> |
<%= link_to 'Back', lorries_path %>

app/views/lorries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lorries</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lorries.each do |lorry| %>
      <tr>
        <td><%= link_to 'Show', lorry %></td>
        <td><%= link_to 'Edit', edit_lorry_path(lorry) %></td>
        <td><%= link_to 'Destroy', lorry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lorry', new_lorry_path %>

app/views/lorries/new.html.erb
<h1>New Lorry</h1>

<%= render 'form', lorry: @lorry %>

<%= link_to 'Back', lorries_path %>

app/views/lorries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_lorry_path(@lorry) %> |
<%= link_to 'Back', lorries_path %>